# Numpy Basics Exercises

Please complete the following exercises **using numpy only**.

# Array Functions
1.Arange([start,] stop[, step],dtype=None)
Nearly identical to Python’s range(). Creates an array of values in the range [start,stop) with the specified step value. Allows non-integer values for start, stop, and step. Default dtype is derived from the start, stop, and step values. create an array with arange.

In [118]:
import numpy as np

In [119]:
# code here (you may create an array of your own choice)

ar1 = np.arange(1,11,1)
print(ar1)
print(ar1.dtype)
print()

# To create array of floats
ar2 = np.arange(1,11,1,dtype = float)
print(ar2)
ar2.dtype

[ 1  2  3  4  5  6  7  8  9 10]
int64

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


dtype('float64')

2.Create arrays with ONES, ZEROS, shape is a number or sequence specifying the dimensions of the array. If dtype is not specified, it defaults to float64.

In [120]:
# code here (you may create an array of your choice of size)

a1= np.ones(5) # one dimensional array
print(a1)
print()

a2 = np.ones((2,3)) # two dimensional array
print(a2)
print()

a3 = np.zeros(4) # one dimensional array
print(a3)
print()


a4 = np.zeros((2,3)) # two dimensional array
print(a4)
print()

# The default type of array elements is float64
#  Let's try one array with type int32

a5 = np.ones(5,dtype = np.int32)
print(a5)
print(a5.dtype)
print()

# shows the shape of the array
a5.shape

[1. 1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]]

[0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[1 1 1 1 1]
int32



(5,)

3.Generate an n by n identity array. The default dtype is float64.

In [121]:
# code here (you may create an array of your choice of size)
# Let's create a four by four two dimensional array
n = 4
np.eye(n)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

4.use empty, full, and fill, max, min, std, mean, var, argmax, linspace

In [122]:
# code here (use the array createed in Question 1 for this)
# Creating an empty array
ar2 = np.empty(6).reshape(2,3)
print(ar2)
print()

#  using full function to create a 3 by 3 array
ar3 = np.full((3,3),5)
print(ar3)
print()

# using fill function to fill the value in previous empty array array
a = np.zeros((3,3))
a.fill(3.0)
print(a)
print()

# Create 2 dimensional array and apply the stat functions

ar5 = np.arange(1,10).reshape(3,3)
print('ar5 = ',ar5)
print()

# Find te max of ar5
max = np.max(ar5)
print('max = ',max)
print()

# Find the min of ar5
min = np.min(ar5)
print('min = ',min)
print()

# Find the standard deviation of ar5
std = np.std(ar5)
print('std = ',std)
print()

# Find the variance of ar5
var = np.var(ar5)
print("var =",var)
print()

# Find the mean of ar5
mean = np.mean(ar5)
print("mean = ",mean)
print()

# Find the var of ar5
var = np.var(ar5)
print('var = ',var)
print()

# Find the  argmax of the ar5

argmax = np.argmax(ar5)
print("argmax = ",argmax)
print()
# Since our array is two dimensional so we can find the poper index by the unravel index

argmax = np.unravel_index(np.argmax(ar5),ar5.shape)
print("argmax = ",argmax)
print()

# linspace
b = np.linspace(0,5,5)
print(b)



[[0. 0. 0.]
 [0. 0. 0.]]

[[5 5 5]
 [5 5 5]
 [5 5 5]]

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]

ar5 =  [[1 2 3]
 [4 5 6]
 [7 8 9]]

max =  9

min =  1

std =  2.581988897471611

var = 6.666666666666667

mean =  5.0

var =  6.666666666666667

argmax =  8

argmax =  (2, 2)

[0.   1.25 2.5  3.75 5.  ]


5. Create the array below with a = np.arange(-15, 15).reshape(5, 6) ** 2

  Rule 1:
  Operations between multiple array objects are first checked for proper shape match.

  Rule 2:
  Mathematical operators (+ - * / exp, log, ...) apply element by element, on the values.

  Rule 3:
  Reduction operations (mean, std, skew, kurt, sum, prod, ...) apply to the whole array, unless an axis is specified.

  Rule 4:
  Missing values propagate unless explicitly ignored (nanmean, nansum, ...).

In [123]:
# code here and try to figure out different functions on your own (as stated in Rule 3, also figure out how to propogate missing values as stated in Rule 4)

a = np.arange(-15,15).reshape(5,6)**2
b = np.arange(-10,20).reshape(5,6)

# performing  functions
sum= a+b
print(sum)
print()

print("a-b  =",a-b)
print()

print("a*b  =",a*b)
print()

print("a/b  =",a/b)
print()

print("exp(a)  = ",np.exp(a))
print()

print("log(a)  =",np.log(a))
print()



[[215 187 161 137 115  95]
 [ 77  61  47  35  25  17]
 [ 11   7   5   5   7  11]
 [ 17  25  35  47  61  77]
 [ 95 115 137 161 187 215]]

a-b  = [[235 205 177 151 127 105]
 [ 85  67  51  37  25  15]
 [  7   1  -3  -5  -5  -3]
 [  1   7  15  25  37  51]
 [ 67  85 105 127 151 177]]

a*b  = [[-2250 -1764 -1352 -1008  -726  -500]
 [ -324  -192   -98   -36     0    16]
 [   18    12     4     0     6    28]
 [   72   144   250   396   588   832]
 [ 1134  1500  1936  2448  3042  3724]]

a/b  = [[-22.5        -21.77777778 -21.125      -20.57142857 -20.16666667
  -20.        ]
 [-20.25       -21.33333333 -24.5        -36.                  inf
   16.        ]
 [  4.5          1.33333333   0.25         0.           0.16666667
    0.57142857]
 [  1.125        1.77777778   2.5          3.27272727   4.08333333
    4.92307692]
 [  5.78571429   6.66666667   7.5625       8.47058824   9.38888889
   10.31578947]]

exp(a)  =  [[5.20305514e+97 1.32348326e+85 2.48752493e+73 3.45466066e+62
  3.54513118e+52 2

<ipython-input-123-dc8d3cf34d9d>:17: RuntimeWarning: divide by zero encountered in divide
  print("a/b  =",a/b)
<ipython-input-123-dc8d3cf34d9d>:23: RuntimeWarning: divide by zero encountered in log
  print("log(a)  =",np.log(a))


In [124]:
#  Reduction operations
from scipy.stats import skew
# mean, std, skew, kurt, sum, prod, .
a = np.arange(-15,15).reshape(5,6)**2
print('mean of a is = ',np.mean(a))
print()

print('standard deviation of a is = ',np.std(a))
print()

print('sum of a is = ',np.sum(a))
print()

print('product of a is = ',np.prod(a))
print()

# Let's define the array containing missng values

a = np.array([1,2,np.nan,4,5,np.nan])
print(a)
print()

# Filling the empty spaces with sum and mean


sum_value = np.nansum(a)
print(sum_value)
print()
filled_sum = np.where(np.isnan(a),sum_value,a)
print(filled_sum)
print()

# Filling with mean in empty spaces

mean_value = np.nanmean(a)
print(mean_value)
print()

filled_mean = np.where(np.isnan(a),mean_value,a)
print(filled_mean)
print()

mean of a is =  75.16666666666667

standard deviation of a is =  67.45323482894567

sum of a is =  2255

product of a is =  0

[ 1.  2. nan  4.  5. nan]

12.0

[ 1.  2. 12.  4.  5. 12.]

3.0

[1. 2. 3. 4. 5. 3.]



6.Create the array below with
                  a = np.arange(-15, 15).reshape(5, 6) ** 2
1. The maximum of each row
2. The mean of each column
3. The position of the overall minimum

In [125]:
# code here and display all 3 values appropriately. You MUST NOT choose an array of your own choice.
a = np.arange(-15,15).reshape(5,6)**2

# Maximum of each row

max = np.max(a,axis = 0)
print('max of each row=', max)
print()

# Mean of each column

mean = np.mean(a,axis = 1)
print('mean of each column is =',mean)
print()

# the position of overall minimum

min = np.unravel_index(np.argmin(a),a.shape)
print('position of overall minimum = ',min)

max of each row= [225 196 169 144 169 196]

mean of each column is = [159.16666667  45.16666667   3.16666667  33.16666667 135.16666667]

position of overall minimum =  (2, 3)


# Array Broadcasting
NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are broadcasted to match the larger arrays, without copying data.

Broadcasting has two rules.

RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE

RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING

In [126]:
#code here # Create 2 arrays A and B with dim (5,4) and (5,) respectively, apply addition and subtraction.
A = np.arange(20).reshape(4,5)
B = np.arange(5).reshape(1,5)
B= B[np.newaxis,:]
tempb = B.repeat(3,axis = 1)
print(tempb)

print(A)
print()
print(B)
print()

#  Array broadcasting
B= B[np.newaxis,:]
tempb = B.repeat(3,axis = 1)
print(tempb)

# Addition of two arrays
print(A+B)
print()

# Subtraction of two arrays
print(A-B)
print()

[[[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[[0 1 2 3 4]]]

[[[[0 1 2 3 4]]

  [[0 1 2 3 4]]

  [[0 1 2 3 4]]]]
[[[[ 0  2  4  6  8]
   [ 5  7  9 11 13]
   [10 12 14 16 18]
   [15 17 19 21 23]]]]

[[[[ 0  0  0  0  0]
   [ 5  5  5  5  5]
   [10 10 10 10 10]
   [15 15 15 15 15]]]]



1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.


In [127]:
# Answer here (use both of these functions on an array of your own choice)

a = np.arange(1,10)
print(a)
print()

print("add=",np.add.reduce(a))
print()

print("product=",np.multiply.reduce(a))
print()

print("min=",np.minimum.reduce(a))
print()

print("max=",np.maximum.reduce(a))
print()

# Accumulate operations

print("accumulate=",np.add.accumulate(a))
print()

print("product=",np.multiply.accumulate(a))
print()

print("min=",np.minimum.accumulate(a))
print()

print("max=",np.maximum.accumulate(a))
print()

[1 2 3 4 5 6 7 8 9]

add= 45

product= 362880

min= 1

max= 9

accumulate= [ 1  3  6 10 15 21 28 36 45]

product= [     1      2      6     24    120    720   5040  40320 362880]

min= [1 1 1 1 1 1 1 1 1]

max= [1 2 3 4 5 6 7 8 9]



### We will work with the following array:

In [128]:
a = np.arange(25).reshape(5, 5)
print(a)
# made a array

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# Use slicing only to select 3rd and last row along with 2nd and last columns

In [129]:
# Getting the required elements
a[[2,-1],:][:,[1,-1]]

array([[11, 14],
       [21, 24]])

# Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]

In [130]:
# The sub array is obtained

a[[0,2,4],:][:,[2,3]]


array([[ 2,  3],
       [12, 13],
       [22, 23]])

# Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]

In [131]:
# Using fancy indexing
a[[1,3,4],:][:,[1,3]]

array([[ 6,  8],
       [16, 18],
       [21, 23]])

# Change the values 1, 10, 19 and 22 in the array to -2

In [132]:
# Answer
a[[0,2,3,4],[1,0,4,2]]= -2
print(a)

# Since the values have been changed in original array

[[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 18 -2]
 [20 21 -2 23 24]]


# Repeat above using boolean indexing

In [133]:
# Using Boolean
a = np.arange(25).reshape(5, 5)
values_to_change = [1, 10, 19, 22]
mask = np.isin(a, values_to_change)
a[mask] = -2
print(a)

[[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 18 -2]
 [20 21 -2 23 24]]


# Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]

In [134]:
# using booliana

a = np.arange(25).reshape(5, 5)
#moving forward, you must use this array for the operations
a[[0,2,3],:][:,[0,3]]


array([[ 0,  3],
       [10, 13],
       [15, 18]])

# Calculating the sum, min and max of all diagonal values

In [135]:
# Answer here
array = np.arange(25).reshape(5, 5)
print(array)

diagonals = np.diag(array)
diagonals

# sum of diagonals
print("sum = ",np.sum(diagonals))
print()

# min of diagonals
print("min = ",np.min(diagonals))
print()

# max of diagonals
print("max = ",np.max(diagonals))
print()

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
sum =  60

min =  0

max =  24



# Calculate the sum of differences between the 2nd row and 2nd last column

In [136]:
array = np.arange(25).reshape(5,5)
print(array)
print()

# Now calculating the sum of difference of second row and last column

row = array[1,:]
column = array[:,-1]
difference = row - column
sum = np.sum(difference)
print(sum)





[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

-35


# Create a new array that is the sum of even rows and odd rows

In [137]:
array
print(array)
print()

# Creating array that is the sum of even rows and odd rows
even_rows_sum = np.sum(array[::2],axis = 0)
print("row containing sum of even rows")
print(even_rows_sum)
print()

odd_rows_sum = np.sum(array[1::2],axis = 0)
print("row containing sum of odd rows")
print(odd_rows_sum)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

row containing sum of even rows
[30 33 36 39 42]

row containing sum of odd rows
[20 22 24 26 28]


## You are done. Good job!