In [ ]:
import numpy as np

# Q1

Statement: Given a 3D NumPy array arr of shape (2, 3, 4), write a code snippet to calculate the sum of all elements in the array.

Sample Input:

In [ ]:
array = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
                  [[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
# Calculate the sum of all the elements in the array
sum_of_elements = np.sum(array)
print(sum_of_elements)
print()


156



# Q2

Statement: Write a NumPy code snippet to create a 4D array arr of shape (2, 3, 4, 5) filled with random integers ranging from 0 to 9.

Sample Output:

In [ ]:
array = np.random.randint(0,10,size = (2,3,4,5))
print(array)
array.shape


[[[[8 5 7 7 2]
   [9 8 0 8 5]
   [3 6 1 8 9]
   [7 6 0 8 3]]

  [[5 9 2 9 9]
   [0 2 3 3 5]
   [1 3 3 3 2]
   [1 7 3 8 0]]

  [[1 2 4 9 2]
   [4 7 5 3 3]
   [9 4 7 8 4]
   [1 7 2 4 5]]]


 [[[1 1 0 6 7]
   [0 1 9 0 9]
   [5 9 4 5 0]
   [3 1 5 2 4]]

  [[4 5 7 7 8]
   [9 9 2 0 4]
   [3 8 2 4 2]
   [1 4 3 7 8]]

  [[6 2 1 0 4]
   [5 6 3 1 0]
   [9 2 0 1 9]
   [6 7 4 2 2]]]]


(2, 3, 4, 5)

# Q3

Statement: Given a 4D NumPy array arr of shape (2, 3, 4, 5), write a code snippet to calculate the mean along the second axis.

Sample Input:

In [ ]:
# using the numpy 4d array created
array
mean = np.mean(array,axis = 1)
print(mean)


[[[4.66666667 5.33333333 4.33333333 8.33333333 4.33333333]
  [4.33333333 5.66666667 2.66666667 4.66666667 4.33333333]
  [4.33333333 4.33333333 3.66666667 6.33333333 5.        ]
  [3.         6.66666667 1.66666667 6.66666667 2.66666667]]

 [[3.66666667 2.66666667 2.66666667 4.33333333 6.33333333]
  [4.66666667 5.33333333 4.66666667 0.33333333 4.33333333]
  [5.66666667 6.33333333 2.         3.33333333 3.66666667]
  [3.33333333 4.         4.         3.66666667 4.66666667]]]


# Q4

Statement: You have collected data from a temperature sensor placed at different locations over a period of time. The recorded temperatures are stored in a 3D NumPy array temps of shape (7, 24, 60), where the dimensions represent the number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the average temperature for each day.

Sample Input:

In [ ]:
# Assume the temperature values range from 0 to 100
# create a numpy array with shape (7,24,60) filled with random temperature values from 0,100

temps = np.random.uniform(0,100,size = (7,24,60))

# To calculate the average temperature for each day we need to find the average of hours and minutes

average_daily_temp = np.mean(temps,axis = (1,2))
print(average_daily_temp)

# we have find the average daily temperature

[51.19847003 48.78533825 50.23046028 49.73161066 49.70623751 50.05791903
 49.28223815]


Sample Output:

array([27.43864059, 26.99643944, 27.10398301, 27.43854821, 26.81072977,
       26.76581481, 27.07946152])

# Q5

Statement: You have collected data from multiple sensors placed in different rooms of a building. The sensor readings are stored in a 4D NumPy array readings of shape (4, 7, 24, 60), where the dimensions represent the number of sensors, number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the maximum reading for each sensor across all days.

In [14]:
# Let's create the 4d array with shape(4,7,24,60) =( 4 sensors, 7 days ,24 hours, 60 minutes)
array = np.random.randint(0,100,size = (4,7,24,60))

# To calculate the maximum value of each sensor we have to find the max of all the days , hours and minutes so

max_value = np.max(array,axis = (1,2,3))
print(max_value)

# we have found the maximum value of each sensor

[99 99 99 99]


# Q6

Statement: You have collected data from a 3D printer that measures the dimensions of printed objects. The recorded dimensions are stored in a 3D NumPy array dimensions of shape (100, 50, 3), where the dimensions represent the number of printed objects, number of measurements for each object, and the three dimensions (length, width, height), respectively. Write a code snippet to calculate the average length, width, and height across all objects.

Sample Inpumt:

In [17]:
# First create a 3d array with shape(100,50,3) = (100 objects, 50 number of measurements and 3 are the number of dimensions)
array = np.random.rand(100,50,3)


# First find out the average of the measurements(axis = 1) and printed objects(axis = 1) to reduce dimensions.This will result in the single object containing three dimension length,width and height

average_dimensions = np.mean(array,axis = (0,1))

# Now extract the individual averages
average_length = average_dimensions[0]
average_width = average_dimensions[1]
average_height = average_dimensions[2]

print("Average Length: ",average_length)
print("Average Width: ",average_width)
print("Average Height: ",average_height)

Average Length:  0.49670469107797516
Average Width:  0.4962398473966467
Average Height:  0.4957918211972099


# Q7

Statement: You are given a 3D NumPy array data of shape (5, 6, 7) representing the sensor readings from multiple sensors placed in different locations over a period of time. Each sensor provides measurements at different time points. Write a code snippet to calculate the following statistics for each sensor:

Total number of measurements

Average measurement value

Standard deviation of measurements

Minimum measurement value

Maximum measurement value

Sample Input:

In [31]:
# Total number of measurements

# Creating random array of shape(5,6,7)
array = np.random.rand(5,6,7)

# Since total measurements = number of measurements*number of time points

total_measurements = array.shape[1]*array.shape[2]
# Now creating an array that contains the measurements of each sensor

total_measurements_persensor = np.full(array.shape[0],total_measurements)
print(total_measurements_persensor)

[42 42 42 42 42]


In [24]:
# Average measurement value
# consider the same matrix

array = np.random.rand(5,6,7)
# To get the average measurements value

average_measurements = np.mean(array,axis = (1,2))
print(average_measurements)

[0.41961795 0.43038251 0.50487724 0.47326354 0.50969429]


In [26]:
# Standard deviation measurement value
# consider the same matrix

array = np.random.rand(5,6,7)
std_deviation = np.std(array,axis = (1,2))
print(std_deviation)

[0.27889638 0.26335611 0.29826913 0.26774636 0.31147859]


In [27]:
# Minimum measurement value

array = np.random.rand(5,6,7)
min_measurement_value = np.min(array,axis = (1,2))
print(min_measurement_value)


[0.03959451 0.00685093 0.03077382 0.00340816 0.01408235]


In [28]:
#  Maximum measurement value

array = np.random.rand(5,6,7)
max_measurement_value = np.max(array,axis = (1,2))
print(max_measurement_value)

[0.97740176 0.99049139 0.98031038 0.97963837 0.96187493]
