In [ ]:
import numpy as np

### Basic Array Creation

# Creatation of List
create List in python? # Check Type of list

In [ ]:
mlist = [1,2,3,4,5,6,35,"string"]

In [ ]:
type(mlist)
# Function type, Shows the type of the data structure

list

# Creatation of Arrays
1.Create an array containing 10 elements

2.Checking array "TYPE"

3.Check data type of array elements

4.Array dim

5.Array Shape

6.Bytes per element

7.Total bytes in an Array

In [ ]:
# Let's do all these steps in similar order

# 1. Creation of array containing ten elements

ar1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(ar1)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
type(ar1)
# 2. Shows the type of array

numpy.ndarray

In [ ]:
ar1.dtype
# 3. Shows the types of elements in array

dtype('int64')

In [ ]:
ar1.ndim
# 4.  Shows the dim of the array

1

In [ ]:
ar1.shape
# 5. Shows the shape of the array

(10,)

In [ ]:
ar1.itemsize
# 6. Every item has 8 bytes

8

In [ ]:
ar1.nbytes
# 7. Total bytes in an array

80

In [ ]:
# Create 'float' array and repeat above mention steps 1-7
# Repeating all the steps in the same order on floats

ar2 = np.array([1,2,3,4,5,6,7,8,9,10],dtype = float)
print(ar2)
# 2. Creates an array containing float elements

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
# Let's do all the remaining operations in a single cell
# Since we cannot use the type function for an array containing float elements

# 3. Checking the data type of array elements
a1 = ar2.dtype
print ("The type of elements in array is",a1)
print()

# 4. Checking the dim of the array
a2 = ar2.ndim
print ("The array is of dimension",a2)
print()

# 5. Checking the shape of the array
a3 = ar2.shape
print ("The array has",a3,"elements")
print()

# 6. Checking the memory used by each element
a4 = ar2.itemsize
print ("Every item has",a4,"bytes")
print()

# 7. Checking the total memory consumed by an array
a5 = ar2.nbytes
print ("Total bytes in an array is",a5,"bytes")



The type of elements in array is float64

The array is of dimension 1

The array has (10,) elements

Every item has 8 bytes

Total bytes in an array is 80 bytes


-Try to assign a float into an int32

-Use .fill function # fill has the same behavior


In [ ]:
# First creating int32 elements
ar3 = np.array([1,2,3,4,5,6,7,8,9,10],dtype = 'int32')
print(ar3)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Lets assign a float into int32
ar3[1] = 3.5
print(ar3)
print()
#  Shows that we array cannot except a float value into int32

# Now fill the value with any int
ar3.fill(-5.0)
print(ar3)
# See that assigning a float to a int32 and filling an array with float has the same behaviour

[ 1  3  3  4  5  6  7  8  9 10]

[-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]


-. Add two  arrays

-. Multiple both arrays

-.Use ** operator in array operation

-.Create array from 0.0 to 11.0

-.Multiply entire array with a scalar value
 c = (2.0 * np.pi)

-.Use np.arrange function to create an array with step of 0.5 from 1.0 to 3.0

In [ ]:
# Let's do all the operations in a single cell

ar4 = np.array([1,2,3,4,5,6])
ar5 = np.array([7,8,9,10,11,12])

# Adding ar4 and ar5
print(ar4 + ar5)
print()

# Multiplying ar4 and ar5
print(ar4 * ar5)
print()

# Using the ar5 as the power of ar4
print(ar4 ** ar5)
print()

[ 8 10 12 14 16 18]

[ 7 16 27 40 55 72]

[         1        256      19683    1048576   48828125 2176782336]



In [ ]:
# Creating array from 0.0 to 11.0
ar6 = np.array([0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0])
print(ar6)
print()

# To multipy array with constant lets first define a constant
c = 2.0*np.pi
ar6  = ar6* c
print(ar6)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

[ 0.          6.28318531 12.56637061 18.84955592 25.13274123 31.41592654
 37.69911184 43.98229715 50.26548246 56.54866776 62.83185307]


In [ ]:
# Creating array using np.arange function and set stepsize = 0.5
ar7 = np.arange(1.0,3.0,0.5)
print(ar7)

[1.  1.5 2.  2.5]


# Slicing
var[lower:upper:step]
• Extracts a portion of a sequence by specifying a lower and upper bound.

• The lower-bound element is included, but the upper-bound element is not included.

• Mathematically: [lower, upper). The step value specifies the stride between elements.

1. Etract array indices from 1 to 3:
2. Use negative indices as well
3. Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements
4. Grab last two elements
5. Grab every other element
6. slicing the last two elements returns the data there
7. Can we insert an iterable of length two? or a scalar value
8.Arrays created by slicing share data with the originating array. Changing values in a slice also changes the original array.
For example create a slice containing two elements of a changing b changed a! Have an experiment
9. if an array a = [[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]] extract values from row 3 to onward and from col 0, 2 and 5
10. Perform some masking on a = np.arange(0,36).reshape(6,6)
with mask = np.array([1, 0, 1, 0, 0, 1])


In [ ]:
# Lets create an array first
ar8 = np.array([1,2,3,4,5,6,7,8,9,10])
              #
# 1. Extracting elements from indices 1 to 3
sliced_ar = ar8[1:4]
print(sliced_ar)
print()

# 2.  Extracting elements from indices 2 to 6 using negative indixing
sliced_ar = ar8[-8:-3]
print(sliced_ar)

[2 3 4]

[3 4 5 6 7]


In [ ]:
# 3.  Assuming the omitted boundaries are the beginning or end grab first 3 elements

ar8 = np.array([1,2,3,4,5,6,7,8,9,10])
print(ar8)
print()

#  Grabing first three elements from beginning
sliced_ar = ar8[:3]
print(sliced_ar)
print()

#  Grabing first three elements from negative indexing

sliced_ar = ar8[-10:-7]
print(sliced_ar)

[ 1  2  3  4  5  6  7  8  9 10]

[1 2 3]

[1 2 3]


In [ ]:
ar8 = np.array([1,2,3,4,5,6,7,8,9,10])
print(ar8)
print()

# 4. Grabing last two elements
sliced_ar = ar8[-2:]
print(sliced_ar)
print()

# 5. Grabing every other element
sliced_ar = ar8[::2]
print(sliced_ar)
print()



[ 1  2  3  4  5  6  7  8  9 10]

[ 9 10]

[1 3 5 7 9]



In [ ]:
ar8 = np.array([1,2,3,4,5,6,7,8,9,10])
print(ar8)
print()

# 6. slicing the last two elements returns the data there
sliced_ar = ar8[-2:]
print(sliced_ar)
print()

# 7. Yes we can isert an iterable of length two
iterable = [1,2]
np.insert(ar8,2,iterable)
print(ar8)
print()
# Check we have inserted an iterable of length two



[ 1  2  3  4  5  6  7  8  9 10]

[ 9 10]

[ 1  2  3  4  5  6  7  8  9 10]



In [ ]:
# 8. Yes changing data in slice array changed in original array, let's see how
ar9 = np.array([0,1,2,3,4,5,6,7,8,9])
print(ar9)
print()

# define a sliced array
sliced_ar = ar9[1:5]
print(sliced_ar)
#  Now change the data in sliced array
sliced_ar[0:2]= 50
print(sliced_ar)
print()

# Now check the original array
print(ar9)


# See the data has been changed in the original array

[0 1 2 3 4 5 6 7 8 9]

[1 2 3 4]
[50 50  3  4]

[ 0 50 50  3  4  5  6  7  8  9]


In [ ]:
#  9. Now get the required results from 1 array and 0,2,4 columns

a = np.array([[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]])
a[1,[0,2,4]]

array([1, 3, 5])

In [ ]:
# 10,performing masking
a = np.arange(0,36).reshape(6,6)
print(a)
print()
mask = np.array([1, 0, 1, 0, 0, 1],dtype=bool)
a = a[mask,2]
print(a)

# Getting the first third and sixth element from the second column using mask

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

[ 2 14 32]


### Create a 2-D array where the first row goes from 10 to 80 exclusive with steps of 5 and 2nd row goes from 5 to 47 exclusive with steps of 3

In [ ]:
# Creating a matrix
ar10 = np.array([np.arange(10,80,5),np.arange(5,47,3)])
print(ar10)

# Check the dimension of the matrix
print(ar10.ndim)

[[10 15 20 25 30 35 40 45 50 55 60 65 70 75]
 [ 5  8 11 14 17 20 23 26 29 32 35 38 41 44]]
2


### Now use indexing to select the 5th 7th and 11th columns

In [ ]:
# Selecting 5,7,and 11th column
ar10[0:,[5,7,11]]

array([[35, 45, 65],
       [20, 26, 38]])

### Select the 2nd row and fourth-last to second-last columns

In [ ]:
ar10[1,-4:-1]
# gives the result

array([35, 38, 41])

### Select 3rd to 3rd last columns skipping every second column

In [ ]:
ar10[0:,2:-2:2]
# Gives the required result

array([[20, 30, 40, 50, 60],
       [11, 17, 23, 29, 35]])

###  Select 3rd to 3rd last columns skipping every second column but in reverse order

In [ ]:
ar10[0:,-12:-2:2][::-1]

#  gives the required result

array([[11, 17, 23, 29, 35],
       [20, 30, 40, 50, 60]])

### Zip Operations on Numpy Arrays
Use a zip function on two arrys.

Create another array which would be the sum of corresponding elements of two arrays using for loop.

In [ ]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

# Using zip function to combine both arrays
# First convert them into arrays

a = np.array(a)
b = np.array(b)
c = np.array(list(zip(a,b)))
print(c)

[[1 2]
 [2 3]
 [3 4]
 [4 5]]


In [ ]:
# Create another array which would be the sum of corresponding elements of two arrays using for loop.
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]
c = []
for i,j in (zip(a,b)):
    c.append(i+j)
print(c)

# Result achieved

[3, 5, 7, 9]


In [ ]:
# Thanks